projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - codegen/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: codegen/API.ts
        docsFilePath: codegen/graphql
        region: us-east-1
        apiId: z7pynuevvzgkfggjcgrondcmhu
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
